format = """
[░▒▓](#a3aed2)\
[ $username on $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
\n$character
"""

right_format = """
$terraform
$python
$time\
[ ](fg:#1d2230)\
"""
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ](bg:#a3aed2 fg:#090c0c)'
disabled = false

[os]
format = '[$symbol](bg:#a3aed2 fg:#090c0c)'
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch 